// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqX3CJfolH-SANx6S3jIcu6PgLKdSJdvs',
    appId: '1:100324421948:web:c5e13f612c6ed8e675ae39',
    messagingSenderId: '100324421948',
    projectId: 'rent-me-65e2a',
    authDomain: 'rent-me-65e2a.firebaseapp.com',
    storageBucket: 'rent-me-65e2a.appspot.com',
    measurementId: 'G-62ELCPG6WH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxm3uQxeDmz2IuxwU28LR6y6c3LTTZgdI',
    appId: '1:100324421948:android:a1065d23fbd3a3b475ae39',
    messagingSenderId: '100324421948',
    projectId: 'rent-me-65e2a',
    storageBucket: 'rent-me-65e2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwlWw_wYS13VG6bKiuqbEvk6Si3pglo3A',
    appId: '1:100324421948:ios:76cb97c4d2c6102975ae39',
    messagingSenderId: '100324421948',
    projectId: 'rent-me-65e2a',
    storageBucket: 'rent-me-65e2a.appspot.com',
    iosBundleId: 'com.example.rentMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwlWw_wYS13VG6bKiuqbEvk6Si3pglo3A',
    appId: '1:100324421948:ios:0764e91ee963f8fd75ae39',
    messagingSenderId: '100324421948',
    projectId: 'rent-me-65e2a',
    storageBucket: 'rent-me-65e2a.appspot.com',
    iosBundleId: 'com.example.rentMe.RunnerTests',
  );
}
